code --install-extension 13xforever.language-x86-64-assembly
code --install-extension 8amjp.charactercount
code --install-extension adpyke.vscode-sql-formatter
code --install-extension AffenWiesel.matlab-formatter
code --install-extension alexcvzz.vscode-sqlite
code --install-extension aliariff.vscode-erb-beautify
code --install-extension asvetliakov.vscode-neovim
code --install-extension atian25.copy-syntax
code --install-extension be5invis.toml
code --install-extension bierner.markdown-mermaid
code --install-extension blackmist.LinkCheckMD
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension bpruitt-goddard.mermaid-markdown-syntax-highlighting
code --install-extension christian-kohler.path-intellisense
code --install-extension codezombiech.gitignore
code --install-extension CraigMaslowski.erb
code --install-extension cschlosser.doxdocgen
code --install-extension cweijan.vscode-mysql-client2
code --install-extension danielpinto8zz6.c-cpp-compile-run
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension donjayamanne.githistory
code --install-extension donjayamanne.python-environment-manager
code --install-extension donjayamanne.python-extension-pack
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension fabiospampinato.vscode-todo-plus
code --install-extension formulahendry.code-runner
code --install-extension formulahendry.docker-explorer
code --install-extension formulahendry.vscode-mysql
code --install-extension foxundermoon.shell-format
code --install-extension freebroccolo.reasonml
code --install-extension Gimly81.matlab
code --install-extension GitHub.copilot
code --install-extension GitHub.copilot-labs
code --install-extension GitHub.github-vscode-theme
code --install-extension GitHub.vscode-pull-request-github
code --install-extension golang.go
code --install-extension golang.go-nightly
code --install-extension GraphQL.vscode-graphql
code --install-extension GraphQL.vscode-graphql-syntax
code --install-extension hackwaly.ocaml
code --install-extension hediet.vscode-drawio
code --install-extension humao.rest-client
code --install-extension jakebathman.mysql-syntax
code --install-extension James-Yu.latex-workshop
code --install-extension jeff-hykin.better-cpp-syntax
code --install-extension jrebocho.vscode-random
code --install-extension kaiwood.endwise
code --install-extension kenhowardpdx.vscode-gist
code --install-extension KevinRose.vsc-python-indent
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension magicstack.MagicPython
code --install-extension marp-team.marp-vscode
code --install-extension mechatroner.rainbow-csv
code --install-extension mhutchie.git-graph
code --install-extension michelemelluso.code-beautifier
code --install-extension mohsen1.prettify-json
code --install-extension mosapride.zenkaku
code --install-extension ms-azuretools.vscode-docker
code --install-extension MS-CEINTL.vscode-language-pack-ja
code --install-extension ms-dotnettools.vscode-dotnet-runtime
code --install-extension ms-mssql.data-workspace-vscode
code --install-extension ms-mssql.mssql
code --install-extension ms-mssql.sql-bindings-vscode
code --install-extension ms-mssql.sql-database-projects-vscode
code --install-extension ms-python.black-formatter
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools-themes
code --install-extension ms-vscode.makefile-tools
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vscode.sublime-keybindings
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension ms-vsliveshare.vsliveshare-audio
code --install-extension mtxr.sqltools
code --install-extension nickfode.latex-formatter
code --install-extension njpwerner.autodocstring
code --install-extension oderwat.indent-rainbow
code --install-extension phr0s.bib
code --install-extension PKief.material-icon-theme
code --install-extension pmneo.tsimporter
code --install-extension pnp.polacode
code --install-extension quicktype.quicktype
code --install-extension rbbit.typescript-hero
code --install-extension rebornix.ruby
code --install-extension redhat.java
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.LiveServer
code --install-extension ronaldosena.arduino-snippets
code --install-extension rust-lang.rust-analyzer
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension sianglim.slim
code --install-extension sibiraj-s.vscode-scss-formatter
code --install-extension sidthesloth.html5-boilerplate
code --install-extension stevensona.character-count
code --install-extension tcwalther.cython
code --install-extension tomoyukim.vscode-mermaid-editor
code --install-extension torn4dom4n.latex-support
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vstirbu.vscode-mermaid-preview
code --install-extension wayou.vscode-todo-highlight
code --install-extension wholroyd.jinja
code --install-extension wingrunr21.vscode-ruby
code --install-extension withfig.fig
code --install-extension xabikos.JavaScriptSnippets
code --install-extension xaver.clang-format
code --install-extension xdebug.php-debug
code --install-extension xshrim.txt-syntax
code --install-extension yzane.markdown-pdf
code --install-extension yzhang.markdown-all-in-one
code --install-extension ZainChen.json
code --install-extension Zignd.html-css-class-completion
code --install-extension zxh404.vscode-proto3
