tap "golangci/tap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "ktr0731/evans"
tap "rcmdnk/file"
tap "reviewdog/tap"
brew "bazelisk"
brew "ca-certificates"
brew "cabocha"
brew "libpng"
brew "freetype"
brew "pcre2"
brew "glib"
brew "pkg-config"
brew "pixman"
brew "cairo"
brew "circleci"
brew "cmake"
brew "libnghttp2"
brew "openssl@1.1"
brew "xz"
brew "dart-sdk"
brew "direnv"
brew "icu4c"
brew "node"
brew "firebase-cli"
brew "fzf"
brew "gcc"
brew "gh"
brew "giflib"
brew "git"
brew "git-flow"
brew "glow"
brew "go"
brew "hdf5"
brew "helm"
brew "helmfile"
brew "hugo"
brew "jpeg"
brew "jq"
brew "julia"
brew "kube-linter"
brew "kubernetes-cli"
brew "libev"
brew "libfido2"
brew "pango"
brew "librsvg"
brew "readline"
brew "sqlite"
brew "llvm"
brew "lsd"
brew "lua"
brew "luajit"
brew "mas"
brew "protobuf"
brew "zlib"
brew "mysql"
brew "neovim"
brew "nginx"
brew "openssl@3"
brew "nodebrew"
brew "nodenv"
brew "nvm"
brew "openjdk"
brew "openjdk@11"
brew "postgresql@14"
brew "protoc-gen-go"
brew "pstree"
brew "pyenv"
brew "ruby-build"
brew "rbenv"
brew "redis"
brew "ruby"
brew "rust"
brew "shellcheck"
brew "sl"
brew "telnet"
brew "tig"
brew "tmux"
brew "tree"
brew "webp"
brew "yarn"
brew "golangci/tap/golangci-lint"
brew "heroku/brew/heroku"
brew "ktr0731/evans/evans"
brew "rcmdnk/file/brew-file"
brew "reviewdog/tap/reviewdog"
cask "datagrip"
cask "dotnet-sdk"
cask "fig"
cask "figma"
cask "font-hack-nerd-font"
cask "goland"
cask "google-chrome"
cask "google-cloud-sdk"
cask "intellij-idea"
cask "kube-cluster"
cask "kubenav"
cask "mactex-no-gui"
cask "postman"
cask "rubymine"
cask "visual-studio-code"
mas "Bear", id: 1091189122
mas "GoodNotes", id: 1444383602
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Microsoft Excel", id: 462058435
mas "Microsoft Outlook", id: 985367838
mas "Numbers", id: 409203825
mas "OneDrive", id: 823766827
mas "Pages", id: 409201541
mas "Slack", id: 803453959
mas "Twitter", id: 1482454543
mas "Xcode", id: 497799835
