name: "Build Test with Docker"
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2
      - name: "Clone Repository"
        run: git clone https://github.com/Okabe-Junya/dotfiles.git
      - name: "Move Directory"
        run: mv dotfiles ~/dotfiles
      - name: "Initialize"
        run: docker run --rm -it -v ~/dotfiles:/dotfiles okabejunya/dotfiles:latest make
