name: reviewdog
on:
  pull_request:
    branches:
      - main

jobs:
  shellcheck:
    name: "reviewdog shellcheck"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          path: "."
          pattern: "*.sh"
          exclude: "./.git/*" #
          check_all_files_with_shebangs: "false"
