name: shellcheck

on:
  pull_request:
    branches:
      - main

jobs:
  shellcheck:
    name: reviewdog / shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: shellcheck
        uses: reviewdog/action-shellcheck@4c07458293ac342d477251099501a718ae5ef86e # v1.32.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          path: "."
          pattern: |
            "*.sh"
            "*.zsh"
          exclude: "./.git/*"
          check_all_files_with_shebangs: "false"
