name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run install script
        run: ./install.zsh --non-interactive --skip-brew-bundle
        shell: zsh {0}
        timeout-minutes: 10

      - name: Validate Brewfile
        run: brew bundle list --file=install/Brewfile > /dev/null
        shell: zsh {0}

  readme-installation-test:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Serve install.zsh locally
        run: |
          python3 -m http.server 8888 &
          sleep 1
        shell: zsh {0}

      - name: Run remote-style installation
        run: curl -L http://localhost:8888/install.zsh | zsh -s -- --non-interactive --skip-brew-bundle
        shell: zsh {0}
        timeout-minutes: 10

      - name: Validate Brewfile
        run: brew bundle list --file=$HOME/dotfiles/install/Brewfile > /dev/null
        shell: zsh {0}
